function emptyChart(canvas,message){const ctx=canvas.getContext('2d'),dpr=devicePixelRatio||1,w=canvas.clientWidth||400,h=canvas.clientHeight||240;
canvas.width=w*dpr;
canvas.height=h*dpr;
ctx.scale(dpr,dpr);
ctx.clearRect(0,0,w,h);
ctx.fillStyle=getComputedStyle(document.body).getPropertyValue('--muted')||'#64748b';
ctx.font='14px Inter';
ctx.textAlign='center';
ctx.fillText(message,w/2,h/2)}function drawBarChart(canvas,labels,values){if(!values.length||values.every(v=>v===0)){emptyChart(canvas,'Sem dados para exibir');
return}const ctx=canvas.getContext('2d'),dpr=devicePixelRatio||1,w=canvas.clientWidth,h=canvas.clientHeight;
canvas.width=w*dpr;
canvas.height=h*dpr;
ctx.scale(dpr,dpr);
ctx.clearRect(0,0,w,h);
const max=Math.max(...values,1),pad=35,bottom=h-30,step=(w-pad*2)/values.length,barW=Math.min(46,step*.55);
values.forEach((v,i)=>{const bh=(v/max)*(h-65),x=pad+i*step+(step-barW)/2,y=bottom-bh;
ctx.fillStyle='#2f6fed';
ctx.fillRect(x,y,barW,bh);
ctx.fillStyle='#64748b';
ctx.font='11px Inter';
ctx.textAlign='center';
ctx.fillText(labels[i],x+barW/2,h-10);
ctx.fillStyle='#0f172a';
ctx.fillText(v,x+barW/2,y-6)})}async function renderReport(){try{const r=await EdgeAPI.get('/reports');
document.getElementById('report-stats').innerHTML=[['Câmeras cadastradas',r.cameras],['Câmeras ativas',r.active_cameras],['Usuários cadastrados',r.users],['Usuários ativos',r.active_users],['Usuários online',r.online_users],['Alertas registrados',r.alerts],['Alertas abertos',r.open_alerts],['Tempo total',`${(r.total_seconds/3600).toFixed(1)} h`]].map(x=>`<div class="stat"><div class="label">${x[0]}</div><div class="value">${x[1]}</div><div class="hint">${x[1]===0?'Sem dados cadastrados':'Dados registrados no sistema'}</div></div>`).join('');
drawBarChart(document.getElementById('usage-chart'),['Uso'],[r.total_seconds]);
drawBarChart(document.getElementById('alert-chart'),['Crítico','Alto','Normal'],['Crítico','Alto','Normal'].map(k=>r.alert_levels[k]||0))}catch(e){showToast(e.message)}}window.addEventListener('edge-data-ready',renderReport);
document.getElementById('apply-report').onclick=()=>{renderReport();
showToast('Relatório atualizado.')};
document.getElementById('export-report').onclick=async()=>{try{const data={generatedAt:new Date().toISOString(),report:await EdgeAPI.get('/reports'),alerts:await EdgeAPI.get('/alerts')};
const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');
a.href=URL.createObjectURL(blob);
a.download='edgesecurity-relatorio.json';
a.click();
URL.revokeObjectURL(a.href)}catch(e){showToast(e.message)}};
