async function initConfig(){try{const u=await EdgeAPI.get('/me');
document.getElementById('setting-name').value=u.nome;
document.getElementById('setting-email').value=u.email;
document.getElementById('theme').value=localStorage.getItem('edge_theme')||'light';
document.getElementById('font-size').value=localStorage.getItem('edge_font')||'normal';
document.getElementById('save-account').onclick=async()=>{try{await EdgeAPI.put(`/users/${u.id}`,{nome:document.getElementById('setting-name').value.trim(),email:document.getElementById('setting-email').value.trim(),cargo:u.cargo,status:u.status,permissoes:u.permissoes,cameras:u.cameras,senha:null});
const s=JSON.parse(localStorage.getItem('edge_session')||sessionStorage.getItem('edge_session'));
s.nome=document.getElementById('setting-name').value.trim();
s.email=document.getElementById('setting-email').value.trim();
(localStorage.getItem('edge_session')?localStorage:sessionStorage).setItem('edge_session',JSON.stringify(s));
showToast('Dados da conta salvos.')}catch(e){showToast(e.message)}};
document.getElementById('save-appearance').onclick=()=>{localStorage.setItem('edge_theme',document.getElementById('theme').value);
localStorage.setItem('edge_font',document.getElementById('font-size').value);
document.body.classList.toggle('dark',document.getElementById('theme').value==='dark');
document.body.classList.toggle('large',document.getElementById('font-size').value==='large');
showToast('Preferências salvas.')};
if(u.cargo!=='administrador')document.querySelector('.admin-only')?.remove()}catch(e){showToast(e.message)}}window.addEventListener('edge-data-ready',initConfig);
